/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dataaccess.User;
import forms.AdminDashboard;
import forms.StaffDashboard;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class JeepneyLogReg extends javax.swing.JFrame {

    /**
     * Creates new form JeepneyLogReg
     */
    public JeepneyLogReg() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblRoles = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jtfUsername = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        cmbLoginAs = new javax.swing.JComboBox<>();
        lblSubtitle = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setText("Jeepney Terminal Organizer");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        lblRoles.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblRoles.setForeground(new java.awt.Color(51, 51, 51));
        lblRoles.setText("Login As:");
        jPanel1.add(lblRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        txtPassword.setFont(new java.awt.Font("Noto Sans Lisu", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.setText("Password:");
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 80, -1));

        txtUsername.setFont(new java.awt.Font("Noto Sans Lisu", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 0, 0));
        txtUsername.setText("Username:");
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 80, -1));

        btnLogin.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 240, 50));
        jPanel1.add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 290, 50));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo-new.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 220, 190));

        cmbLoginAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        jPanel1.add(cmbLoginAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 110, 40));

        lblSubtitle.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(153, 153, 153));
        lblSubtitle.setText("Login to Continue");
        jPanel1.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));
        jPanel1.add(jpfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 290, 50));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
    String username = jtfUsername.getText();
    String password = new String(jpfPassword.getPassword());
    String selectedRole = cmbLoginAs.getSelectedItem().toString();


    if (username.isEmpty() || password.isEmpty() || selectedRole.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields.");
    return;
    }

    User dao = new User();
    String role = dao.login(username, password);

    if (role != null) {

        if (selectedRole.equalsIgnoreCase(role)) {

            JOptionPane.showMessageDialog(this, "Login successful!");

            // Open the correct dashboard based on the database role
            if (role.equalsIgnoreCase("admin")) {
                AdminDashboard adminDashboard = new AdminDashboard();
                adminDashboard.setVisible(true);
            } else if (role.equalsIgnoreCase("staff")) {
                StaffDashboard staffDashboard = new StaffDashboard();
                staffDashboard.setVisible(true);
            }

            // Close the login form after successful login
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this,
                    "Role mismatch. Selected role does not match your account.");
        }

    } else {
        // Username or password is incorrect
        JOptionPane.showMessageDialog(this, "Invalid username or password.");
}
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeepneyLogReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeepneyLogReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeepneyLogReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeepneyLogReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JeepneyLogReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbLoginAs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfUsername;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRoles;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
